version: 2
jobs:
  build:
    branches:
      only:
        - "master"
    docker:
      - image: nexela/factorio-lua-env:0.0.1
    steps:
      - checkout
      #- run: ln -s /root/project /usr/local/share/lua/5.2/__stdlib__
      - run: wget -q --no-check-certificate -O .luacheckrc https://raw.githubusercontent.com/Nexela/Factorio-luacheckrc/master/.luacheckrc
      - run: luacheck .
      - run: make quick
      - store_artifacts:
          path: /root/project/.build/artifacts
